# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stern_brocot
#'
#' Approximates a floating-point number to arbitrary uncertainty (vectorized version).
#'
#' This implementation is based on the Stern-Brocot tree algorithm as described in:
#' - Forišek M. Approximating rational numbers by fractions. In International Conference on Fun with Algorithms 2007 Jun 3 (pp. 156-165). Berlin, Heidelberg: Springer Berlin Heidelberg.
#' - Stolzenburg F. Harmony perception by periodicity detection. Journal of Mathematics and Music. 2015 Sep 2;9(3):215-38.
#'
#' @param x Vector of numbers to convert to rational fractions.
#' @param lower_uncertainty Lower uncertainty bounds (scalar or vector).
#' @param upper_uncertainty Upper uncertainty bounds (scalar or vector).
#'
#' @return A data frame with results and metadata about the tree path.
#' @export
stern_brocot <- function(x, lower_uncertainty, upper_uncertainty) {
    .Call(`_SternBrocot_stern_brocot`, x, lower_uncertainty, upper_uncertainty)
}

