# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stern_brocot_cpp <- function(x, valid_min, valid_max) {
    .Call(`_SternBrocot_stern_brocot_cpp`, x, valid_min, valid_max)
}

